version: "3.3"

services:
  library:
    restart: always
    image: sameersbn/postgresql:10-2
    environment:
      - PG_TRUST_LOCALNET=true
      - DB_NAME=library
      - DB_USER=postgres
      - DB_PASS=postgres
      - PG_RUNDIR=/run/postgres
      - PG_LOGDIR=/var/log/postgres
    ports:
      - "5432:5432"
    volumes:
      - data:/var/lib/postgresql
      - logs:/var/log/postgresql

  backend:
    image: libraryapplication
    ports:
      - "8080:8080"
    depends_on:
      - library
      - redis
  redis:
    image: "redis:alpine"

  frontend:
    image: libraryapplicationfe
    ports:
      - "4200:80"
    depends_on:
      - backend


volumes:
  data:
  logs: